export const fiveDaysForecast = [
  {
    date: "8 Sep",
    weekDay: "Wednesday",
    icon: 4,
    maxTemp: { c: 27, f: 80 },
    minTemp: { c: 17, f: 62 },
    weatherText: "Intermittent clouds",
  },
  {
    date: "9 Sep",
    weekDay: "Thursday",
    icon: 11,
    maxTemp: { c: 22, f: 71 },
    minTemp: { c: 16, f: 60 },
    weatherText: "Intermittent clouds",
  },
  {
    date: "10 Sep",
    weekDay: "Friday",
    icon: 3,
    maxTemp: { c: 21, f: 69 },
    minTemp: { c: 15, f: 59 },
    weatherText: "Intermittent clouds",
  },
  {
    date: "11 Sep",
    weekDay: "Saturday",
    icon: 7,
    maxTemp: { c: 21, f: 69 },
    minTemp: { c: 13, f: 55 },
    weatherText: "Intermittent clouds",
  },
];

export const todayForecast = {
  weekDay: "Tuesday",
  data: " 7 Sep",
  icon: 1,
  weatherText: "Sunny",
  currentTemp: { c: 25, f: 77 },
  maxTemp: { c: 28, f: 82 },
  minTemp: { c: 16, f: 60 },
  humidity: 57,
  wind: { m: "3.2 km/h", i: "5.4 mi/h" },
};

export const icons = {
  1: "sunny",
  2: "sunny",
  3: "cloudy_sunny",
  4: "cloudy_sunny",
  5: "cloudy_sunny",
  6: "cloud",
  7: "cloud",
  8: "cloud_foggy",
  11: "fog",
  12: "drop",
  13: "raining_sun",
  14: "raining_sun",
  15: "cloudy_lightning",
  16: "lightning",
  17: "lightning",
  18: "rain",
  19: "snow",
  20: "raining_sun",
  21: "raining_sun",
  22: "cloud_snowflake",
  23: "cloud_snowflake",
  24: "snowflake",
  25: "snow",
  26: "rain",
  29: "snow",
  30: "hot",
  31: "snowflake",
  32: "wind",
  33: "moon",
  34: "moon",
  35: "cloudy_moon",
  36: "cloudy_moon",
  37: "fog",
  38: "cloudy_moon",
  39: "night_raining",
  40: "night_raining",
  41: "lightning",
  42: "cloudy_lightning",
  43: "snow",
  44: "cloud_snowflake",
};
